name: Deploy to VPS

on:
  push:
    branches:
      - main  # 触发部署的分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH into VPS and deploy
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_PRIVATE_KEY }}
        script: |
          cd /root/random-key-app
          git pull origin main
          npm install
          pm2 restart myapp
